"""initial schema

Revision ID: 076f6ab98187
Revises: a1e0d2c93b57
Create Date: 2026-07-11 20:18:47.533389
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from geoalchemy2 import Geometry

revision: str = '076f6ab98187'
# The Geometry columns below need the postgis extension, which a1e0d2c93b57
# creates. This used to be None and the extension came from a Docker-only init
# hook, so the chain was not self-sufficient on managed Postgres.
down_revision: Union[str, None] = 'a1e0d2c93b57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('PROGRAM_MANAGER', 'FIELD_CREW', 'QUALITY_REVIEWER', 'COMPLIANCE_REVIEWER', name='role'), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_user_email'), 'app_user', ['email'], unique=True)
    op.create_table('audit_event',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_table('corridor',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('circuit_id', sa.String(), nullable=False),
    sa.Column('span_label', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('voltage_kv', sa.Integer(), nullable=False),
    sa.Column('centerline', Geometry(geometry_type='LINESTRING', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_corridor_centerline', 'corridor', ['centerline'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_corridor_circuit_id'), 'corridor', ['circuit_id'], unique=False)
    op.create_geospatial_table('environmental_constraint',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('WATER_BUFFER', 'HABITAT', 'STEEP_SLOPE', 'NO_WORK_ZONE', 'ACCESS_RESTRICTED', 'HFTD', name='constraint_category'), nullable=False),
    sa.Column('severity', sa.Enum('ADVISORY', 'BLOCKING', name='constraint_severity'), nullable=False),
    sa.Column('geometry', Geometry(geometry_type='POLYGON', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('effective_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_end', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_environmental_constraint_geometry', 'environmental_constraint', ['geometry'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_table('sync_attempt',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACCEPTED', 'DUPLICATE', 'CONFLICT', 'REJECTED', name='sync_status'), nullable=False),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('correlation_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'idempotency_key', name='uq_idempotency')
    )
    op.create_index(op.f('ix_sync_attempt_idempotency_key'), 'sync_attempt', ['idempotency_key'], unique=False)
    op.create_table('work_order',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('priority', sa.Enum('ROUTINE', 'ELEVATED', 'HAZARD', name='work_order_priority'), nullable=False),
    sa.Column('corridor_id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['corridor_id'], ['corridor.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_order_reference'), 'work_order', ['reference'], unique=True)
    op.create_geospatial_table('treatment_plan',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('work_order_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SCHEDULED', 'IN_PROGRESS', 'APPLIED', 'AWAITING_VERIFICATION', 'EFFECTIVE', 'PARTIALLY_EFFECTIVE', 'INEFFECTIVE', 'INCONCLUSIVE', 'FOLLOW_UP_PLANNED', 'CLOSED', name='treatment_status'), nullable=False),
    sa.Column('planned_geometry', Geometry(geometry_type='POLYGON', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('target_condition', sa.Text(), nullable=False),
    sa.Column('method_category', sa.Enum('MANUAL', 'MECHANICAL', 'HERBICIDE', 'BIOLOGICAL', 'CULTURAL', name='method_category'), nullable=False),
    sa.Column('required_evidence', sa.JSON(), nullable=False),
    sa.Column('verification_policy', sa.JSON(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_treatment_plan_planned_geometry', 'treatment_plan', ['planned_geometry'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_table('treatment_execution',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('actual_geometry', Geometry(geometry_type='POLYGON', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('crew_id', sa.String(), nullable=True),
    sa.Column('applicator_record', sa.JSON(), nullable=False),
    sa.Column('constraint_acknowledged', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('coverage_ratio', sa.Float(), nullable=True),
    sa.Column('local_revision', sa.Integer(), nullable=False),
    sa.Column('server_revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['crew_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['treatment_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_treatment_execution_actual_geometry', 'treatment_execution', ['actual_geometry'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_table('verification_observation',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('condition', sa.Text(), nullable=True),
    sa.Column('regrowth_observed', sa.Boolean(), nullable=False),
    sa.Column('compatible_cover', sa.Boolean(), nullable=False),
    sa.Column('followup_geometry', Geometry(geometry_type='POLYGON', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('reviewer_id', sa.String(), nullable=True),
    sa.Column('conclusion', sa.Enum('EFFECTIVE', 'PARTIALLY_EFFECTIVE', 'INEFFECTIVE', 'INCONCLUSIVE', name='verification_conclusion'), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['treatment_plan.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_verification_observation_followup_geometry', 'verification_observation', ['followup_geometry'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_table('evidence_item',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('execution_id', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('PHOTO_BEFORE', 'PHOTO_AFTER', 'CLEARANCE_MEASUREMENT', 'NOTE', 'FORM', name='evidence_type'), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('geolocation', Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('upload_status', sa.Enum('PENDING', 'UPLOADING', 'STORED', 'FAILED', name='upload_status'), nullable=False),
    sa.Column('checksum', sa.String(), nullable=True),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['treatment_execution.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_evidence_item_geolocation', 'evidence_item', ['geolocation'], unique=False, postgresql_using='gist', postgresql_ops={})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_geospatial_index('idx_evidence_item_geolocation', table_name='evidence_item', postgresql_using='gist', column_name='geolocation')
    op.drop_geospatial_table('evidence_item')
    op.drop_geospatial_index('idx_verification_observation_followup_geometry', table_name='verification_observation', postgresql_using='gist', column_name='followup_geometry')
    op.drop_geospatial_table('verification_observation')
    op.drop_geospatial_index('idx_treatment_execution_actual_geometry', table_name='treatment_execution', postgresql_using='gist', column_name='actual_geometry')
    op.drop_geospatial_table('treatment_execution')
    op.drop_geospatial_index('idx_treatment_plan_planned_geometry', table_name='treatment_plan', postgresql_using='gist', column_name='planned_geometry')
    op.drop_geospatial_table('treatment_plan')
    op.drop_index(op.f('ix_work_order_reference'), table_name='work_order')
    op.drop_table('work_order')
    op.drop_index(op.f('ix_sync_attempt_idempotency_key'), table_name='sync_attempt')
    op.drop_table('sync_attempt')
    op.drop_geospatial_index('idx_environmental_constraint_geometry', table_name='environmental_constraint', postgresql_using='gist', column_name='geometry')
    op.drop_geospatial_table('environmental_constraint')
    op.drop_index(op.f('ix_corridor_circuit_id'), table_name='corridor')
    op.drop_geospatial_index('idx_corridor_centerline', table_name='corridor', postgresql_using='gist', column_name='centerline')
    op.drop_geospatial_table('corridor')
    op.drop_table('audit_event')
    op.drop_index(op.f('ix_app_user_email'), table_name='app_user')
    op.drop_table('app_user')
    # ### end Alembic commands ###
